monkey patch atexit, since it seems to be gernerating this error in same cases (but all the tests still pass)
Ran 2083 tests in 8.913s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/mnt/hgfs/workspace/pyramid/pyramid/scripts/pserve.py", line 400,
in _remove_pid_file
current_pid = os.getpid()
AttributeError: 'NoneType' object has no attribute 'getpid'