backport #1325
The copyright symbol causes this error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2559: ordinal not in range(128)

Replaced non-ascii copyright character with HTML equivalent.

Added required notes to changes/contributors file.